package genome

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"go/ast"
	_ "go/ast"
	"go/printer"
	_ "go/token"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/saayn-agent/pkg/model"
)

// RegistryManager handles the lifecycle of the genome.json
type RegistryManager struct {
	Registry *model.Registry
	FilePath string
}

// NewRegistry initializes a new registry from scanned nodes
func NewRegistry(scannedNodes []*model.Node, path string) *RegistryManager {
	reg := &model.Registry{
		ProjectName: "SAAYN-Genome",
		Nodes:       make(map[string]model.Node),
	}

	rm := &RegistryManager{Registry: reg, FilePath: path}

	for _, n := range scannedNodes {
		// 🧠 FIX: Use the UUID already generated by the scanner!
		// Do not call uuid.New() here or you'll lose the original identity.

		if n.AST != nil {
			n.LogicHash = rm.NormalizeAndHash(n)
		}

		n.Version = 1
		n.LastModified = time.Now()
		reg.Nodes[n.UUID] = *n // Key by the scanner-provided UUID
	}
	fmt.Println()
	return rm
}

// NormalizeAndHash turns a function body into a stable LogicHash
func (rm *RegistryManager) NormalizeAndHash(n *model.Node) string {
	if n.AST == nil || n.Fset == nil {
		return ""
	}

	var buf strings.Builder
	conf := &printer.Config{Mode: printer.RawFormat, Tabwidth: 8}

	switch node := n.AST.(type) {
	case *ast.FuncDecl:
		// 🧠 V5 FIX: We need to hash the signature AND the body.
		// We create a shallow copy to avoid mutating the actual AST.
		cp := *node
		cp.Doc = nil // ⛔ Ignore comments so doc-only changes don't trigger AI costs
		_ = conf.Fprint(&buf, n.Fset, &cp)

	case *ast.GenDecl:
		cp := *node
		cp.Doc = nil
		_ = conf.Fprint(&buf, n.Fset, &cp)

	default:
		_ = conf.Fprint(&buf, n.Fset, node)
	}

	body := buf.String()

	// COLLAPSE WHITESPACE
	re := regexp.MustCompile(`\s+`)
	body = re.ReplaceAllString(body, " ")
	body = strings.TrimSpace(body)

	// CALCULATE HASH
	hash := sha256.Sum256([]byte(body))
	hashStr := fmt.Sprintf("%x", hash)

	// Pretty Print logic...
	return hashStr
}

// Save persists the registry to the genome.json file
func (rm *RegistryManager) Save() error {
	data, err := json.MarshalIndent(rm.Registry, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(rm.FilePath, data, 0644)
}

// Load reads an existing registry from disk
func Load(path string) (*RegistryManager, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var reg model.Registry
	if err := json.Unmarshal(data, &reg); err != nil {
		return nil, err
	}
	return &RegistryManager{Registry: &reg, FilePath: path}, nil
}
